{{- define "ops360lib.external-secret.tpl" }}
{{- range .Values.secrets | default list }}
{{ $securityManagerName := .securityManagerName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.k8sNamespace | default "ops360" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .k8sSecretStoreName }}
    kind: SecretStore
  target:
    name: {{ .k8sSecretName }}
    creationPolicy: Owner
  data:
  {{- range .entries }}
  - secretKey: {{ .k8sSecretKey }}
    remoteRef:
      key: {{ $securityManagerName }}
      property: {{ .securityManagerKey }}
  {{- end }}
{{- end }}
{{- end }}