{{/* Generate the environment variables based on enabled dependencies */}}
{{- define "ops360lib.secret-data.tpl" }}
{{- if .Values.keystoreEnabled }}
{{ (.Files.Glob "files/keystore.jks").AsSecrets }}
{{- end }}
{{- end -}}

{{- define "ops360lib.secret-header.tpl" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Chart.Name }}
    suite: ops360
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- end -}}

