{{- define "ops360lib.secret-store.tpl" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreName }}
  namespace: {{ .Values.k8s_namespace | default "ops360" }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | default "us-east-1"}}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName }}
{{- end -}}